---
# tasks file for init_gitea

- name: Je verifie que le gitea est accessible sur son url
  ansible.builtin.uri:
    url: "{{ gitea_url }}"
    status_code: 200
    validate_certs: false
  register: check_gitea_url

- name: J'initialise le gitea
  ansible.builtin.uri:
    url: "{{ gitea_url }}"
    method: POST
    validate_certs: false
    body_format: raw
    body: "db_type=sqlite3&db_host=localhost%3A3306&db_user=root&db_passwd=&db_name=gitea&ssl_mode=disable&db_schema=&charset=utf8&db_path={{ gitea_init_pathdb }}&app_name=Gitea%3A+Git+with+a+cup+of+tea&repo_root_path={{ gitea_init_pathroot }}&lfs_root_path={{ gitea_init_pathlfs }}&run_user=git&domain={{ gitea_init_fqdn }}&ssh_port={{ gitea_init_ssh_cport }}&http_port={{ gitea_init_http_cport }}&app_url={{ gitea_init_url }}&log_root_path={{ gitea_init_pathlog }}&smtp_addr=&smtp_port=&smtp_from=&smtp_user=&smtp_passwd=&enable_federated_avatar=on&enable_open_id_sign_in=on&enable_open_id_sign_up=on&default_allow_create_organization=on&default_enable_timetracking=on&no_reply_address=noreply.localhost&password_algorithm=pbkdf2&admin_name={{ gitea_admin_name }}&admin_passwd={{ gitea_admin_pass }}&admin_confirm_passwd={{ gitea_admin_pass }}&admin_email={{ gitea_admin_email }}"
  when: check_gitea_url.status == 200
